# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('inicio', models.DateField()),
                ('leitura', models.DateField(blank=True, null=True)),
                ('causa_afastamento', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mandato',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('participacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parlamentar',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('nome_completo', models.CharField(max_length=150)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('forma_tratamento', models.CharField(max_length=15)),
                ('foto_url', models.CharField(max_length=100)),
                ('pagina_url', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=70)),
                ('sigla_partido', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('mandato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parlamentares.Mandato')),
            ],
        ),
        migrations.CreateModel(
            name='Suplente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_participacao', models.CharField(max_length=20)),
                ('parlamentar_id', models.BigIntegerField()),
                ('mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suplentes', to='parlamentares.Mandato')),
            ],
        ),
        migrations.AddField(
            model_name='legislatura',
            name='mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legislaturas', to='parlamentares.Mandato'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='parlamentares.Mandato'),
        ),
    ]
