# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='email',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
