# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parlamentares', '0002_auto_20171201_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parlamentar',
            name='sigla_partido',
            field=models.CharField(max_length=10),
        ),
    ]
